gitimeless	ftgen 0, 0, 0, 1, "/Users/j/Documents/PROJECTs/IDRA/_core/__gen/__wav/timeless.wav", 0, 0, 1
gicaes	ftgen 0, 0, 0, 1, "/Users/j/Documents/PROJECTs/IDRA/_core/__gen/__wav/caes.wav", 0, 0, 1
gicatdiodio	ftgen 0, 0, 0, 1, "/Users/j/Documents/PROJECTs/IDRA/_core/__gen/__wav/catdiodio.wav", 0, 0, 1
gicubcatdio	ftgen 0, 0, 0, 1, "/Users/j/Documents/PROJECTs/IDRA/_core/__gen/__wav/cubcatdio.wav", 0, 0, 1
gicubdio	ftgen 0, 0, 0, 1, "/Users/j/Documents/PROJECTs/IDRA/_core/__gen/__wav/cubdio.wav", 0, 0, 1
gicudio	ftgen 0, 0, 0, 1, "/Users/j/Documents/PROJECTs/IDRA/_core/__gen/__wav/cudio.wav", 0, 0, 1
gidente	ftgen 0, 0, 0, 1, "/Users/j/Documents/PROJECTs/IDRA/_core/__gen/__wav/dente.wav", 0, 0, 1
gidiocle	ftgen 0, 0, 0, 1, "/Users/j/Documents/PROJECTs/IDRA/_core/__gen/__wav/diocle.wav", 0, 0, 1
gifruit	ftgen 0, 0, 0, 1, "/Users/j/Documents/PROJECTs/IDRA/_core/__gen/__wav/fruit.wav", 0, 0, 1
gigrembo	ftgen 0, 0, 0, 1, "/Users/j/Documents/PROJECTs/IDRA/_core/__gen/__wav/grembo.wav", 0, 0, 1
gired	ftgen 0, 0, 0, 1, "/Users/j/Documents/PROJECTs/IDRA/_core/__gen/__wav/red.wav", 0, 0, 1
